<[2020-04-03 14:34:55.593951] 잘못된결과분석@naver.com 잘못된출력값 지역구와후보자명이잘못매칭됐습니다.>
<[2020-04-03 15:25:14.151516] 잘못된결과분석@naver.com 컴파일에러 python:can'topenfile'/home/ptython/temp/7777/data/sample_template_04.py':[Errno2]Nosuchfileordirectory>
<[2020-04-03 15:28:05.118016] 잘못된결과분석@naver.com 컴파일에러 python:can'topenfile'/home/jb/ptython/temp/7777/data/sample_template_04.py':[Errno2]Nosuchfileordirectory>
<[2020-04-03 15:29:41.504159] 잘못된결과분석@naver.com 컴파일에러 python:can'topenfile'/home/jb/ptython/tmp/7777/data/sample_template_04.py':[Errno2]Nosuchfileordirectory>
<[2020-04-03 15:31:40.091430] 잘못된결과분석@naver.com 잘못된출력값 지역구와후보자명이잘못매칭됐습니다.>
<[2020-04-10 18:03:35.255922] haneojin@gmail.com 컴파일에러 python:can'topenfile'/tmp/6261/data/3d51176d-3cb6-4abf-96f9-9dd04ca47ebf.py':[Errno2]Nosuchfileordirectory>
<[2020-04-10 18:16:54.412816] haneojin@gmail.com 컴파일에러 python:can'topenfile'/tmp/6261/data/b0a713dd-84a2-4f7b-9090-2f1565d34a2f.py':[Errno2]Nosuchfileordirectory>
<[2020-04-10 18:34:25.291453] haneojin@gmail.com 컴파일에러 python:can'topenfile'/tmp/6261/data/b9cc9d60-fcf2-4666-99e6-c37b17ed2425.py':[Errno2]Nosuchfileordirectory>
<[2020-04-10 18:38:42.140118] haneojin@gmail.com 컴파일에러 python:can'topenfile'/tmp/6261/data/cdfc4da9-acec-44a8-a348-b181bbc01a6b.py':[Errno2]Nosuchfileordirectory>
<[2020-04-13 13:52:58.065432] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/83c4a661-ed31-47f4-9e79-fbcc879ae00d.py",line68,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'>
<[2020-04-13 13:53:37.278359] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/60eb544e-3c5e-47bf-9ca9-fe33d76d96ac.py",line68,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'>
<[2020-04-13 14:03:10.872938] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/1b4a3a7a-5d45-4296-905f-05566b6de1db.py",line70,in<module>data.columnsNameError:name'data'isnotdefined>
<[2020-04-13 14:04:30.793752] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/22bcd56e-7d72-485d-895e-b69bc2e6ab59.py",line55,in<module>dataNameError:name'data'isnotdefined>
<[2020-04-13 14:05:39.014123] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/421ff1c8-b8c4-4fe6-a138-f8f532e10049.py",line55,in<module>dataNameError:name'data'isnotdefined>
<[2020-04-13 14:06:46.434284] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/76f1e7f2-0280-485d-9389-b9f1ebeef053.py",line71,in<module>data.columnsNameError:name'data'isnotdefined>
<[2020-04-13 14:08:42.820222] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/c4f6e569-1d15-4155-9f34-361e900fc919.py",line55,in<module>dataNameError:name'data'isnotdefined>
<[2020-04-13 14:10:48.246833] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/57dd3a8a-4abb-46fe-9777-5e2bf4731783.py",line55,in<module>dataNameError:name'data'isnotdefined>
<[2020-04-13 14:11:56.782473] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/0103a47d-7485-4978-a1d4-1ba4bb235dcc.py",line54,in<module>dataNameError:name'data'isnotdefined>
<[2020-04-13 14:12:46.194684] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/cea768ac-9108-4c71-a639-7a98daebbddb.py",line54,in<module>dataNameError:name'data'isnotdefined>
<[2020-04-13 14:14:02.052390] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/30e17366-6308-4e02-b7cb-e572552fccdd.py",line70,in<module>data.columnsNameError:name'data'isnotdefined>
<[2020-04-13 14:14:40.508020] sy_park@heung.me 정상처리 >
<[2020-04-13 14:15:48.267788] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/4f14d93e-14c4-4cfb-999d-4076de61799e.py",line71,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'>
<[2020-04-13 14:16:34.067524] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/808c120d-b361-493a-ab7b-f4c4db587d3f.py",line71,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'>
<[2020-04-13 14:16:59.870683] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/737bd221-7614-44e9-af3c-aadfa31e5d16.py",line71,in<module>data.head()NameError:name'data'isnotdefined>
<[2020-04-13 14:18:44.864176] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/126b88c0-3a1b-48c2-84e1-7a17324fd407.py",line64,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'Duringhandlingoftheaboveexception,anotherexceptionoccurred:Traceback(mostrecentcalllast):File"/tmp/6301/data/126b88c0-3a1b-48c2-84e1-7a17324fd407.py",line66,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'Duringhandlingoftheaboveexception,anotherexceptionoccurred:Traceback(mostrecentcalllast):File"/tmp/6301/data/126b88c0-3a1b-48c2-84e1-7a17324fd407.py",line68,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'>
<[2020-04-13 14:27:31.294380] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/7e691c12-0e78-459a-ac26-30f108c06cbb.py",line72,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'>
<[2020-04-13 14:28:42.999784] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/7ba13d26-ce56-4626-80b7-68462f365885.py",line72,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'>
<[2020-04-13 14:31:39.504166] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/04712727-dfbf-4c6b-8c17-deffdc3534d4.py",line64,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'Duringhandlingoftheaboveexception,anotherexceptionoccurred:Traceback(mostrecentcalllast):File"/tmp/6301/data/04712727-dfbf-4c6b-8c17-deffdc3534d4.py",line67,in<module>data=pd.read_csv("서울_총선_취합(1).csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]File서울_총선_취합(1).csvdoesnotexist:'서울_총선_취합(1).csv'>
<[2020-04-13 14:50:31.869223] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/f4b66bf5-f5fe-4106-818d-e7db063a7ec6.py",line64,in<module>data=pd.read_csv("train.csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]Filetrain.csvdoesnotexist:'train.csv'Duringhandlingoftheaboveexception,anotherexceptionoccurred:Traceback(mostrecentcalllast):File"/tmp/6301/data/f4b66bf5-f5fe-4106-818d-e7db063a7ec6.py",line67,in<module>data=pd.read_csv("train.csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]Filetrain.csvdoesnotexist:'train.csv'>
<[2020-04-13 14:53:48.829286] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/5a7ab627-2e33-4ecc-933e-f1ed240c97f5.py",line69,in<module>data=pd.read_csv("train.csv")File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line676,inparser_freturn_read(filepath_or_buffer,kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line448,in_readparser=TextFileReader(fp_or_buf,**kwds)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line880,in__init__self._make_engine(self.engine)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1114,in_make_engineself._engine=CParserWrapper(self.f,**self.options)File"/dvote-django/data-election/dataVenv/lib/python3.6/site-packages/pandas/io/parsers.py",line1891,in__init__self._reader=parsers.TextReader(src,**kwds)File"pandas/_libs/parsers.pyx",line374,inpandas._libs.parsers.TextReader.__cinit__File"pandas/_libs/parsers.pyx",line674,inpandas._libs.parsers.TextReader._setup_parser_sourceFileNotFoundError:[Errno2]Filetrain.csvdoesnotexist:'train.csv'>
<[2020-04-13 14:57:03.237606] sy_park@heung.me 컴파일에러 Traceback(mostrecentcalllast):File"/tmp/6301/data/c2a260c6-916a-45fa-8268-32bd724ee0d8.py",line71,in<module>data.head()NameError:name'data'isnotdefined>
